---
slug: tricare
filename: tricare
title: What TriCare Can Do For You
subtitle: TriCare For Life
description: This book explains what Tricare is and what it can do for you.
author: Gerald S. Brown, DP1, USNR-R
copyright: 2014
uuid: 2a1cab03-2eb8-4ba5-a480-96c32cade2e2
pdf_preview_page_range: 1..30
epub_mobi_preview_chapter_range: 0..1
