---
prices:
  -
    code: ebooks
    name: "HTML & Ebook"
    description:
      |
        Optimized for Kindle and iPad
        Almost 9000 pages of content
        Includes a free copy of 1st Edition PDF
    media:
      - html
      - pdf
      - epub
      - mobi
    price: 0

authors:
  -
    name: "Gerald S. Brown"
    image: /images/testimonial_1.png
    contact_email: "info@softcover.io"
    bio:
      |
        Author bio [link](https://www.softcover.io)

hide_custom_domain_footer: false
