---
prices:
  -
    code: ebooks
    name: "HTML & Ebook"
    description:
      |
        Optimized for Kindle and iPad

    media:
      - ebooks
    price: 0

  -

authors:
  -
    name: "Gerald S. Brown"
    image: /images/testimonial_1.png
    contact_email: "tc-info@gerbreown.com"

hide_custom_domain_footer: false
